services:
    db:
        image: postgres
        restart: always
        ports:
            - "127.0.0.1:5432:5432"
        environment:
            POSTGRES_PASSWORD: example
        volumes:
            - "./pgdata:/var/lib/pgdata"
